### ISSUE TITLE
Use vendoring middleware, like `dep`

### ISSUE THREAD

**Issue by otiai10** [otiai10/awsub#60]
# WHAT SHOULD I USE FOR GOLANG VENDROING TOOL!!!!!????!?!??

- dep?

**Comment by otiai10** [comment]
# Problem as is

- `docker/machine` requires `docker/docker` revision https://github.com/moby/moby/commit/bf1345d0b6d91f24e06d05e741897bc83cf8bab4 2018 13 Feb

```toml
[[projects]]
  branch = "master"
  name = "github.com/docker/docker"
  packages = [
    "pkg/term",
    "pkg/term/windows"
  ]
  revision = "bf1345d0b6d91f24e06d05e741897bc83cf8bab4"
```

- On the other hand, `otiai10/daap` wants to have the latest `docker/docker` to use `api/types/volume.VolumeCreateBody`

When using `dep init` and `dep ensure`, the version of `docker/docker` is determined by `docker/machine` and gonna be `bf1345d0b6d91f24e06d05e741897bc83cf8bab4`, then conflicts.

# Wish it would get merged

- https://github.com/docker/machine/pull/4515

# Until merged... 😢 

- `awsub` should be built manually on local with setting specific (the latest) version of `docker/docker` and distribute the built binaries
